### ISSUE TITLE
Channel Topic Updater [Feature Request]

### ISSUE THREAD

**Issue by KurzweilTV** [BillyGalbreath/VS-DiscordBot#1]
Hello, I'm not a C dev, but did some GPTing. How hard would it be to sync the channel topic to the players online?

Something like this I suppose. Love the bot btw.

```
private async Task UpdateDiscordTopicWithPlayerCount()
{
    // Assuming _chatChannel is the channel you want to update
    if (_chatChannel != null)
    {
        int playerCount = Api.World.AllOnlinePlayers.Length; // Get the player count
        string newTopic = $"Players online: {playerCount}";  // Format the new topic

        // Update the channel topic
        await _chatChannel.ModifyAsync(channelProps =>
        {
            channelProps.Topic = newTopic;
        });
    }
}
```

**Comment by BillyGalbreath** [comment]
It's trivial to update the channel topic, however discord has some extremely harsh rate limits for this. It only allows 2 edits every 10 minutes. I do have the player count in the bot's presence, though. It'll say something like `playing with 6 players`
